name: Build module release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 设置为 0 以获取所有标签历史

      - name: Create necessary directories
        run: |
          mkdir -p files/modules
          mkdir -p files/patches/{apks,modules,sdcard,data}
          mkdir -p settings

      - name: Install 7z
        uses: edgarrc/action-7z@v1.0.5

      - name: Get current time
        run: |
          random_number=$((RANDOM % 100))
          timestamp_with_random="$(date +'%Y%m%d')${random_number}"
          echo "$timestamp_with_random" > current_time.txt

      - name: Get latest tag
        id: latest-tag
        run: |
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "$LATEST_TAG" > latest_tag.txt

      - name: Compress prebuilts folder
        run: |
          tar -cJf prebuilts.tar.xz prebuilts/*

      - name: Delete contents of prebuilts folder
        run: |
          rm -rf prebuilts


      - name: Compress repository for each language version
        run: |
            LATEST_TAG=$(cat latest_tag.txt)
            CURRENT_TIME=$(cat current_time.txt)
            languages=("en" "jp" "zh")
            . ./settings/languages.ini
            for lang in "${languages[@]}"; do
              find languages -maxdepth 1 -mindepth 1 -type d ! -name "$lang" -exec rm -rf {} +
              if [ "$lang" = "en" ]; then
                rm -f README.md README_JP.md
              elif [ "$lang" = "jp" ]; then
                rm -f README.md README_EN.md
              elif [ "$lang" = "zh" ]; then
                rm -f README_EN.md README_JP.md
              fi
              if [ -d "languages/$lang" ]; then
                cp "languages/$lang"/* .
                cp "languages/$lang"/custom_script.sh ./settings/
                cp "languages/$lang"/settings.ini ./settings/settings.sh
                rm -rf ./custom_script.sh
                rm -rf ./settings.ini
                rm -rf "languages/$lang"/*
                rmdir "languages/$lang" 
                rmdir languages
                eval "lang_${lang}"
                echo "id=AuroraNasa_Installer" > module.prop
                echo "name=${MODULE_NAME}" >> module.prop
                echo "version=${LATEST_TAG}" >> module.prop
                echo "versionCode=${CURRENT_TIME}" >> module.prop
                echo "author=AuroraNasa" >> module.prop
                echo "description=${MODULE_DES} ${lang}" >> module.prop
                cat module.prop
              fi
              7z a -r -mx9 "ARMIAS_${LATEST_TAG}_${lang}.zip" * -x!*.git* -x!*.zip -x!latest_tag.txt -x!current_time.txt -x!LICENSE
              git checkout -- languages
              git checkout -- README.md README_EN.md README_JP.md
            done

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ARMIAS_*.zip
