name: Compress Repository by Language

on:
  push:
    branches: [ main ] # 根据实际情况替换分支名

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 设置为 0 以获取所有标签历史

      - name: Get latest tag
        id: latest-tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=tag::$LATEST_TAG"

      - name: Compress repository for each language version
        run: |
          languages=("en" "jp" "zh")
          LATEST_TAG=${{ steps.latest-tag.outputs.tag }}
          
          for lang in "${languages[@]}"; do
            find languages -maxdepth 1 -mindepth 1 -type d ! -name "$lang" -exec rm -rf {} +
            rm -f README.md README_*.md
            if [ -d "languages/$lang" ]; then
              mv "languages/$lang"/* .
              rmdir "languages/$lang" 
            fi
            rm -r languages
            zip -r "$LATEST_TAG_$lang.zip" . -x *.git* *.md *.zip
            git checkout -- languages
          done

      - name: Upload zip files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.latest-tag.outputs.tag }}_all_languages
          path: |
            *.zip