name: Compress Repository by Language

on:
  push:
    branches: [ main ] # 根据实际情况替换分支名

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 设置为 0 以获取所有标签历史

      - name: Get latest tag
        id: latest-tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=tag::$LATEST_TAG"

      - name: Compress repository for each language version
        run: |
            languages=("en" "jp" "zh")
            LATEST_TAG=${{ steps.latest-tag.outputs.tag }}
            
            for lang in "${languages[@]}"; do
              # Step 1: Create a temporary list of all directories
              find . -type d -print > directories.txt
              
              # Your existing code to remove non-target languages and other files
              find languages -maxdepth 1 -mindepth 1 -type d ! -name "$lang" -exec rm -rf {} +
              rm -f README.md README_*.md
              if [ -d "languages/$lang" ]; then
                mv "languages/$lang"/* .
                rmdir "languages/$lang" 
              fi
              rm -r languages
              
              # Step 2: Use the temporary list to ensure all directories are added to the zip
              while IFS= read -r dir; do
                # Check if the directory is empty and add it to the zip explicitly if it is
                if [ -d "$dir" ] && [ "$(ls -A $dir)" = "" ]; then
                  zip -r "${LATEST_TAG}_${lang}.zip" "$dir" -x *.git* *.md *.zip
                fi
              done < directories.txt
              
              # Add all other files and non-empty directories to the zip
              zip -r "${LATEST_TAG}_${lang}.zip" . -x *.git* *.md *.zip
              
              # Step 3: Remove the temporary list of directories
              rm directories.txt
              
              # Restore the 'languages' directory for the next iteration
              git checkout -- languages
            done

      - name: Upload zip files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.latest-tag.outputs.tag }}_all_languages
          path: |
            *.zip