name: Compress Repository by Language

on:
  push:
    branches: [ main ] # 根据实际情况替换分支名

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 设置为 0 以获取所有标签历史

      - name: Get latest tag
        id: latest-tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=tag::$LATEST_TAG"

      - name: Compress repository for each language version
        run: |
          languages=("en" "jp" "zh")
          LATEST_TAG=${{ steps.latest-tag.outputs.tag }}
          
          for lang in "${languages[@]}"; do
            # 创建临时目录用于存放当前语言版本的文件
            mkdir "temp_$lang"
            
            # 复制当前语言版本的文件到临时目录
            cp -r languages/"$lang"/* "temp_$lang"/ || true # 忽略复制错误，例如目录不存在
            
            # 删除临时目录中的不必要文件
            rm -f "temp_$lang"/README.md "temp_$lang"/README_*.md "temp_$lang"/*.zip
            
            # 在临时目录中压缩当前语言版本的仓库，并使用最新 tag 命名
            zip -r "${LATEST_TAG}_$lang.zip" "temp_$lang"/* -x *.git*
            
            # 删除临时目录
            rm -rf "temp_$lang"
          done

      - name: Upload zip files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compressed-repository-by-language-and-tag
          path: |
            *.zip