name: Compress Repository by Language

on:
  push:
    branches: [ main ] # 根据实际情况替换分支名

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 设置为 0 以获取所有标签历史

      - name: Get latest tag
        id: latest-tag
        run: |
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "$LATEST_TAG" > latest_tag.txt
      
      - name: Read latest tag
        id: read-latest-tag
        run: |
            LATEST_TAG=$(cat latest_tag.txt)
            echo "Latest tag is: $LATEST_TAG"

      - name: Compress repository for each language version
        run: |
          LATEST_TAG=$(cat latest_tag.txt)
          languages=("en" "jp" "zh")
          
          for lang in "${languages[@]}"; do
            find languages -maxdepth 1 -mindepth 1 -type d ! -name "$lang" -exec rm -rf {} +
            rm -f README.md README_*.md
            if [ -d "languages/$lang" ]; then
              mv "languages/$lang"/* .
              rmdir "languages/$lang" 
            fi
            rm -r languages
            zip -rD "${LATEST_TAG}_${lang}.zip" . -x *.git* *.md *.zip
            git checkout -- languages
          done

          - name: Upload zip files as artifacts
          id: upload-artifacts
          run: |
              LATEST_TAG=$(cat latest_tag.txt)
              ARTIFACT_NAME="${LATEST_TAG}_all_languages"
              mkdir "$ARTIFACT_NAME"
              mv *.zip "$ARTIFACT_NAME"/
              echo "::set-output name=artifact-name::$ARTIFACT_NAME"
          
          # 使用本地命令上传 artifacts，因为我们已经有了所需的文件名
          uses: actions/upload-artifact@v4
          with:
            name: ${{ steps.upload-artifacts.outputs.artifact-name }}
            path: ${{ steps.upload-artifacts.outputs.artifact-name }}