name: Compress Repository by Language

on:
  push:
    branches: [ main ] # 根据实际情况替换分支名

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 设置为 0 以获取所有标签历史

      - name: Get latest tag
        id: latest-tag
        run: |
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "$LATEST_TAG" > latest_tag.txt
      
      - name: Read latest tag
        id: read-latest-tag
        run: |
            LATEST_TAG=$(cat latest_tag.txt)
            echo "Latest tag is: $LATEST_TAG"

      - name: Action 7z
        uses: edgarrc/action-7z@v1.0.5
            
      - name: Compress repository for each language version
        run: |
          LATEST_TAG=$(cat latest_tag.txt)
          languages=("en" "jp" "zh")
          
          for lang in "${languages[@]}"; do
            find languages -maxdepth 1 -mindepth 1 -type d ! -name "$lang" -exec rm -rf {} +
            rm -f README.md README_*.md
            if [ -d "languages/$lang" ]; then
              mv "languages/$lang"/* .
              rmdir "languages/$lang" 
            fi
            rm -r languages
            run: 7z a -tzip -mx9 -m0=lzma2 "${LATEST_TAG}_${lang}.zip" . -x*.git\\* -x*.md -x*.zip
            git checkout -- languages
          done

          - name: Upload zip files as artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ARMIAS_all_languages
            path: |
              *.zip