name: Compress Repository by Language

on:
  push:
    branches: [ main ] # 根据实际情况替换分支名

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 设置为 0 以获取所有标签历史

      - name: Get latest tag
        id: latest-tag
        run: |
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "$LATEST_TAG" > latest_tag.txt

      - name: Create empty folders
        run: |
           mkdir -p files/modules/
           mkdir -p files/patches/
           mkdir -p files/patches/apks
           mkdir -p files/patches/modules
           mkdir -p files/patches/sdcard
           mkdir -p files/patches/data
           mkdir -p settings/
      
      - name: Read latest tag
        id: read-latest-tag
        run: |
            LATEST_TAG=$(cat latest_tag.txt)
            echo "Latest tag is: $LATEST_TAG"

      - name: Action 7z
        uses: edgarrc/action-7z@v1.0.5

      - name: Get current time
        run: |
          CURRENT_TIME=$(date +"%Y%m%d%H%M")
          echo "CURRENT_TIME=$CURRENT_TIME" >> $GITHUB_ENV   

      - name: Compress repository for each language version
        run: |
          
          for lang in "${languages[@]}"; do
            find languages -maxdepth 1 -mindepth 1 -type d ! -name "$lang" -exec rm -rf {} +
            rm -f README.md README_*.md
            if [ -d "languages/$lang" ]; then
              cp "languages/$lang"/* .
              cp "languages/$lang"/custom_script.sh ./settings/
              cp "languages/$lang"/settings.ini ./settings/settings.sh
              rm -rf ./custom_script.sh
              rm -rf ./settings.ini
              rm -rf "languages/$lang"/*
              rmdir "languages/$lang" 
              rmdir languages
              echo "id=AuroraNasa_Installer" > module.prop
              echo "name=Highly customizable automated module installation and configuration module" >> module.prop
              echo "version=${LATEST_TAG} ${GITHUB_SHA:0:8}" >> module.prop
              echo "versionCode=${CURRENT_TIME}" >> module.prop
              echo "author=AuroraNasa" >> module.prop
              echo "description=This module will be automatically deleted after restarting, please do not interfere" >> module.prop
              cat module.prop
              7z a archive.7z curl jq -m0=zstd -mx=22
              rm -rf curl
              rm -rf jq
            fi
            7z a -r -mx9 "ARMIAS_${LATEST_TAG}_${GITHUB_SHA:0:8}_${lang}.zip" * -x!*.git* -x!*.md -x!*.zip -x!latest_tag.txt
            git checkout -- languages
          done

      - name: Upload zip files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ARMIAS_all_languages_versions
          path: |
            *.zip